### PR TITLE
Enable auto scroll when receiving new message

### PR DESCRIPTION
**Pull request by trueblooda**
This functionality was in the code already, it was just commented out.

Adding this feature will help bluebubbles match its iOS design philosophy.

### CODE REVIEW

**Comment by zlshames** [comment]
Hey, can you edit this PR to be to the development branch? I just created it as it probably was needed to properly allow contributors to contribute

**Review by zlshames — COMMENTED** [review]
Also, while this does work, I want to prevent the auto scroll from happening when the user is scrolled up a certain amount of pixels. Could you modify this so that the auto scroll will only occur if the current scroll is within X (maybe 50px) of the bottom?

**Comment by mwaldrich** [comment]
> Hey, can you edit this PR to be to the development branch? I just created it as it probably was needed to properly allow contributors to contribute

Sure, do you mean merge *into* `BlueBubblesServer:development`? Or merge *from* `trueblooda:develoment`?



> Also, while this does work, I want to prevent the auto scroll from happening when the user is scrolled up a certain amount of pixels. Could you modify this so that the auto scroll will only occur if the current scroll is within X (maybe 50px) of the bottom?

Can do, we'll ping you when it's done

**Comment by zlshames** [comment]
> > Hey, can you edit this PR to be to the development branch? I just created it as it probably was needed to properly allow contributors to contribute
> 
> Sure, do you mean merge _into_ `BlueBubblesServer:development`? Or merge _from_ `trueblooda:develoment`?
> 
> > Also, while this does work, I want to prevent the auto scroll from happening when the user is scrolled up a certain amount of pixels. Could you modify this so that the auto scroll will only occur if the current scroll is within X (maybe 50px) of the bottom?
> 
> Can do, we'll ping you when it's done

Switch the destination to the BlueBubblesAndroidApp:development branch. It's ok to push from your master

**Comment by mwaldrich** [comment]
@zlshames We made the scroll change. We found that a scroll threshold of 50px was wayyyy too small. It wouldn't scroll one message above. We made the threshold 2000px which will auto-scroll you when you're looking about a page of messages up from the bottom

**Comment by mwaldrich** [comment]
We also change the merge branch

**Review by zlshames — APPROVED** [review]

**Pull request merged**
